mtce/urls.py
from django.urls import path

from jchart.views import ChartView

from . import views

from .charts import *



def here(*a, **kw):
    line_chart = RadarChart()
    return ChartView.from_chart(line_chart)(*a, **kw)



app_name = 'mtce'
urlpatterns = [
    path('', views.index, name='index'),
    path('comparison/<int:comparison_id>/', views.corpus_metrics, name='comparison_index'),

    path('pairwise/<int:comparison_id>/', views.pairwise_index, name='pairwise_index'),
    path('pairwise/<int:comparison_id>/diff/', views.pairwise_diff, name='pairwise_diff'),

    path('comparison/<int:comparison_id>/sentences/', views.sentences, name='comparison_sentences'),

    path('comparison/<int:comparison_id>/sentences/<str:orderby>/<str:first>/<str:diff>/<str:dir>/<int:beg>/<int:end>/', views.sentences_query, name="comparison_sentences_query"),

    path('system/<int:system_id>/', views.system_index, name='system_index'),
    path('system/<int:system_id>/sentences/', views.system_sentences, name='system_sentences'),




   # path('show_sentences/<int:comparison_id>/', views.show_sentences, name="show_sentences"),

   # path('charts/line_chart/', here, name='line_chart'),


   # path('help', views.help, name='help'),
   # path('edit', views.edit, name='edit'),

]

mtcepy_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mtce/', include('mtce.urls')),
    path('nested_admin/', include('nested_admin.urls')),
]

mtce/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.

from django.http import HttpResponse
from .models import Comparison, Checkpoint, MTSystem
from .evaluators import METRICS
from .charts import *
from .sentence_listing import get_all_sentences
from .pairwise_diff import *
import random

from .ngrams import get_all_confirmed_ngrams, get_all_unconfirmed_ngrams

def get_comparisons():
    return Comparison.objects.all() #order_by('name') \
       # .annotate(documents=Count('document')) \
       # .annotate(total_sentences=Count('document__sentence'))
    # tasks_table = TaskTable(tasks)

def index(request):
    """
    The initial dashboard view with a list of tasks
    """
    comparisons = get_comparisons()
    return render(
        request,
        'mtce/index.html',
        {'comparisons': comparisons,
         'active': 'index',
         },
    )

def corpus_metrics(request, comparison_id, system=None):

    comp = get_object_or_404(Comparison, pk=comparison_id)

    metrics = METRICS
    systems_checkpoints = comp.systems_checkpoints()
    if system is not None:
        systems_checkpoints = [(s,ch) for s,ch in systems_checkpoints if s == system]

    systems_checkpoints_metricvalues = [ (s,ch,[ round(ch.get_metric_value(m),2) for m in metrics]) for s,ch in systems_checkpoints ]

    pass_args = {
                   'active':"corpus_metrics",  # for menu
                   'comparison': comp,
                   'systems_checkpoints_metricvalues': systems_checkpoints_metricvalues,
                   'metrics':metrics,
                   'metric_bar_charts': [ MetricBarChart(metric,[(a,b,c[i]) for a,b,c in systems_checkpoints_metricvalues]) \
                                                         for i,metric in enumerate(metrics) ],
                   'system': system,
                   }
    return render(request,
                  'mtce/corpus_metrics.html',
                   pass_args ,
                  )

def system_index(request, system_id):
    system = get_object_or_404(MTSystem, pk=system_id)
    return corpus_metrics(request, system.comparison.id, system)



def sentences_query(request, comparison_id, orderby, first, diff, dir, system=None, beg=0, end=100):
    comp = get_object_or_404(Comparison, pk=comparison_id)

    sentences = get_all_sentences(comp,system)

    if sentences == []:
        return HttpResponse("")

    if orderby == "document":
        if dir == "desc":
            sentences = sentences[::-1]
    elif orderby == "random":
        random.shuffle(sentences)
    else:
        _, metric = orderby.split(">>>")
        _, cp = first.split(">>>")
        cp = int(cp)
        indeces = [ s.id for s in sentences[0]]
        first_ind = indeces.index(cp)
        if diff == 'max-others':
            others = [ s.id for s in sentences[0] if s.id != cp and s.has_metrics ]
            other_ind = [ indeces.index(o) for o in others ]
            print(other_ind)
            def orderkey(sents):
                return sents[first_ind].orderkey(metric) - max(sents[i].orderkey(metric) for i in other_ind)
        elif diff != "-":
            _, diff = diff.split(">>>")
            diff = int(diff)
            diff_ind = indeces.index(diff)
            def orderkey(sents):
                return sents[first_ind].orderkey(metric) - sents[diff_ind].orderkey(metric)
        else:
            def orderkey(sents):
                return sents[first_ind].orderkey(metric)

        if dir == "desc":
            reverse = True
        else:
            reverse = False
        sentences = sorted(sentences, key=orderkey, reverse=reverse)

    sentences = sentences[beg:end]
    if sentences == []:
        return HttpResponse("")
    metrics = []
    for s in sentences[0]:
        if s.has_metrics:
            metrics = s.metrics
    pass_args = {
                   'active':"sentences",  # for top menu
                   'comparison': comp,
                   'system': system,
                   'sentences': sentences,
                   'first_sentences': sentences[0],
                   'checkpoint_names': [ s.name for s in sentences[0] if s.has_metrics ],
                   'metrics': metrics,
                    'metrics_available': metrics != [],
                   }
    return render(request,
                  'mtce/sentences_tables.html',
                   pass_args,
                  )



def sentences(request, comparison_id, system=None):

    comp = get_object_or_404(Comparison, pk=comparison_id)

    sentences = get_all_sentences(comp,system)[:200]
    pass_args = {
                   'active':"sentences",  # for top menu
                   'comparison': comp,
                   'system': system,
                   'sentences': sentences,
                   'first_sentences': sentences[0],
                   'checkpoint_names': [ s.name for s in sentences[0] if s.has_metrics ],
                   'metrics': sentences[0][-1].metrics,
                   }
    return render(request,
                  'mtce/sentences.html',
                   pass_args,
                  )

def system_sentences(request, system_id):
    system = get_object_or_404(MTSystem, pk=system_id)
    return sentences(request, system.comparison.id, system)



def pairwise_index_args(comp, system):
    metrics = METRICS
    systems_checkpoints = comp.systems_checkpoints()
    if system is not None:
        systems_checkpoints = [(s,ch) for s,ch in systems_checkpoints if s == system]

    systems_checkpoints_metricvalues = [ (s,ch,[ round(ch.get_metric_value(m),2) for m in metrics]) for s,ch in systems_checkpoints ]

    pass_args = {
                   'active':"pairwise",  # for menu
                   'comparison': comp,
                   'systems_checkpoints_metricvalues': systems_checkpoints_metricvalues,
                   'metrics':metrics,
#                   'metric_bar_charts': [ MetricBarChart(metric,[(a,b,c[i]) for a,b,c in systems_checkpoints_metricvalues]) \
#                                                         for i,metric in enumerate(metrics) ]+[RadarChart()],
                   'system': system,
                   }
    return pass_args

def pairwise_index(request, comparison_id, system=None):
    comp = get_object_or_404(Comparison, pk=comparison_id)
    pass_args = pairwise_index_args(comp, system)
    return render(request,
                  'mtce/pairwise_index.html',
                   pass_args ,
                  )



def pairwise_diff(request, comparison_id, system=None):
    comp = get_object_or_404(Comparison, pk=comparison_id)
    checkpoint_A, checkpoint_B = map(int,request.POST.getlist("choice[]"))
    A = get_object_or_404(Checkpoint, pk=checkpoint_A)
    B = get_object_or_404(Checkpoint, pk=checkpoint_B)
    A.nicename = A.nice_name()
    B.nicename = B.nice_name()
    pass_args = pairwise_index_args(comp, system)


    def open_toks(fn):
        with open(fn,"r") as f:
            return [l.split() for l in f.readlines()]

    reference = open_toks(A.reference())
    transA = open_toks(A.translationfile())
    transB = open_toks(B.translationfile())

    conf_ngrams = get_all_confirmed_ngrams(reference, transA, transB, beg=0, end=10)
    unconf_ngrams = get_all_unconfirmed_ngrams(reference, transA, transB, beg=0, end=10)

    pa = {
        'sent_level_charts':sentence_level_charts(A, B),
        'bootstrap_charts': bootraps(A, B),
        'checkpoint_A': A,
        'checkpoint_B': B,
        'confirmed_ngrams': conf_ngrams,
        'unconfirmed_ngrams': unconf_ngrams,
    }
    pass_args.update(pa)
    return render(request,
                  'mtce/pairwise_diff.html',
                  pass_args
                  )

mtce/templates/mtce/base.html
{# Load the tag library #}
{% load static %}
{% load i18n %}
{% load bootstrap_themes %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>MTCE-py</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
	    {# Load CSS and JavaScript #}
		{% bootstrap_javascript %}
            <script></script>
      {# % bootstrap_css % #}
            <script></script>
      {# % bootstrap_styles theme='flatly' type='css' % #}
      <script></script>

          <link rel="stylesheet" href="{% static 'mtce/bootstrap.css' %}" media="screen">
      <link rel="stylesheet" href="{% static 'mtce/custom.min.css' %}" media="screen">
      {% bootstrap_script use_min=False %}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </head>
    <body>

    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
<a class="nav-link {% if active == "index" %}table-primary{% endif %}" href="{% url 'mtce:index' %}" style="font-size:30px">MTCE-py</a>
     {% comment %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  {% endcomment %}


        {% block top_menu %}{% endblock %}

</nav>

    <div class="container">
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
        {% block base_content %}{% endblock %}
    </div>



	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script src="{% static 'mtce/jquery.min.js' %}"></script>
    <script src="{% static 'mtce/popper.min.js' %}"></script>
     <script src="{% static 'mtce/bootstrap.min.js' %}"></script>
     <script src="{% static 'mtce/custom.js' %}"></script>

	</body>
</html>

mtce/templates/mtce/comparison_base.html
{% extends "mtce/base.html" %}
{% load jchart %}


{% block top_menu %}
    {% include "mtce/overview_top_menu.html" %}
{% endblock top_menu %}

{% block base_content %}

    {% comment %}
<h2>{{ comparison.name }}
    {% if system %}
      <small class="text-muted">{{ system.name }}</small>
    {% endif %}
</h2>
{% endcomment %}

{% if comparison.description %}
    <p><b>Description:</b> {{ comparison.description }}</p>
{% endif %}


    {% block comparison_content %}{% endblock comparison_content %}


{% endblock base_content %}

mtce/templates/mtce/comparison_detail.html
{% extends "mtce/base.html" %}



{% block content %}

<h1>{{ comparison.name }}</h1>

{% if comparison.description %}
    <p>{{ comparison.description }}</p>
{% endif %}




<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active show" data-toggle="tab" href="#home">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#profile">Source and Reference</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Disabled</a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
    <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 41px, 0px);">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Separated link</a>
    </div>
  </li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active show" id="home">

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">MT System</th>
      <th scope="col">Checkpoint</th>
        {% for metric in metrics %}
          <th scope="col">{{ metric }}</th>
        {% endfor %}
    </tr>
  </thead>
  <tbody>
  {% for sys,cp,metricvalues in systems_checkpoints_metricvalues %}
    <tr class="table-light">
        <th scope="row"><a href="{% url 'mtce:system_detail' sys.id %}">{{ sys }}</a></th>
      <td>{{ cp }}</td>
        {% for mv in metricvalues %}
          <td>{{ mv }}</td>
        {% endfor %}
    </tr>
  {% endfor %}
  </tbody>
</table>



  </div>
  <div class="tab-pane fade" id="profile">
      {% include "mtce/source_reference.html" with list_source_reference=list_source_reference %}
  <div class="tab-pane fade" id="dropdown1">
    <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork.</p>
  </div>
  <div class="tab-pane fade" id="dropdown2">
    <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater.</p>
  </div>
</div>



{% endblock %}

mtce/templates/mtce/comparison_overview.html
{% extends "mtce/base.html" %}
{% load jchart %}


{% block menu %}
    {% include "mtce/menu.html" %}
{% endblock menu %}

{% block content %}

<h1>{{ comparison.name }}</h1>

{% if comparison.description %}
    <p>{{ comparison.description }}</p>
{% endif %}

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#home">Corpus Metrics</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#sentences">Sentences</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Paired bootstrap</a>
  </li>
    {% comment %}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Separated link</a>
    </div>
    {% endcomment %}
  </li>
</ul>

<div id="myTabContent" class="tab-content">
    {% comment %}
    #############################################
    barplots
    #############################################
    {% endcomment %}

    {% comment %}
    <div class="tab-pane fade show active" id="home">
    {% endcomment %}
<div class="tab-pane fade" id="home">
    <div id="accordion">
    {% for chart in metric_bar_charts %}
  <div class="card">
    <div class="card-header" id="heading{{ forloop.counter }}">
      <h5 class="mb-0">
        <button class="btn btn-link nav nav-tab" data-toggle="collapse" data-target="#collapse{{ forloop.counter }}" aria-expanded="{% if forloop.first == True %}true{% else %}false{% endif %}" aria-controls="collapse{{ forloop.counter }}">
            {{ chart.title }}
        </button>
      </h5>
    </div>

    <div id="collapse{{ forloop.counter }}" class="collapse{% if forloop.first == True %} show{% endif %}" aria-labelledby="heading{{ forloop.counter }}" data-parent="#accordion">
      <div class="card-body">
          {{ chart.as_html }}
      </div>
    </div>
  </div>
    {% endfor %}
    </div>


    {% comment %}
    #############################################
    Corpus metrics table
    #############################################
    {% endcomment %}

<table class="table table-hover">

<thead>
<tr>
  <th scope="col">MT System</th>
  <th scope="col">Checkpoint</th>
    {% for metric in metrics %}
      <th scope="col">{{ metric }}</th>
    {% endfor %}
</tr>
</thead>

<form action="{% url 'mtce:index' %}" method="post">
<tbody>
{% csrf_token %}
  {% for sys,cp,metricvalues in systems_checkpoints_metricvalues %}
    <tr class="table-light">
        <th scope="row">
            <input type="checkbox" name="choice" id="choice_{{ cp.id }}" value="{{ cp.id }}">
            <label for="choice{{ forloop.counter }}">
                <a href="{% url 'mtce:system_detail' sys.id %}">{{ sys }}</a>
            </label>
        </th>
      <td>{{ cp }}</td>
        {% for mv in metricvalues %}
          <td>{{ mv }}</td>
        {% endfor %}
     {% comment %}   <td><a href="../../../admin/mtce/comparison/{{ sys.id }}/change/">Edit</a></td>
     {% endcomment %}
    </tr>
  {% endfor %}

  </tbody>
</table>
<button type="submit" class="btn btn-primary">Compare selected</button>
</form>

  {% comment %}

    <p>
<a href="../../../admin/mtce/comparison/{{ sys.id }}/change/">Edit</a>
    </p>

{% endcomment %}

</div>



{% comment %}  <div class="tab-pane fade" id="sentences">
{% endcomment %}
  <div class="tab-pane fade show active" id="sentences">


  {% comment %}
  Sentences:
  {% endcomment %}


      {% include 'mtce/show_sentences.html' %}




  </div>
</div>

{% endblock %}

mtce/templates/mtce/corpus_metrics.html
{% extends "mtce/pairwise_index.html" %}


{% block sentence_level_charts %}


    {% comment %}
    #############################################
    barplots
    #############################################
    {% endcomment %}

    {% comment %}
    <div class="tab-pane fade show active" id="home">
    {% endcomment %}
        {% comment %}
    <div id="accordion">
    {% for chart in metric_bar_charts %}
  <div class="card">
    <div class="card-header" id="heading{{ forloop.counter }}">
      <h5 class="mb-0">
        <button class="btn btn-link nav nav-tab" data-toggle="collapse" data-target="#collapse{{ forloop.counter }}" aria-expanded="{% if forloop.first == True %}true{% else %}false{% endif %}" aria-controls="collapse{{ forloop.counter }}">
            {{ chart.title }}
        </button>
      </h5>
    </div>

    <div id="collapse{{ forloop.counter }}" class="collapse{% if forloop.first == True %} show{% endif %}" aria-labelledby="heading{{ forloop.counter }}" data-parent="#accordion">
      <div class="card-body">
          {{ chart.as_html }}
      </div>
    </div>
  </div>
    {% endfor %}
    </div>
     {% endcomment %}


<div class="container">
    <div class="row">
        {% for chart in metric_bar_charts %}
            <div class="col-6">
                <h4>
                    {{ chart.title }}
                </h4>
                {{ chart.as_html }}
            </div>
        {% endfor %}
    </div>
</div>


{% endblock sentence_level_charts %}

mtce/templates/mtce/index.html
{% extends "mtce/base.html" %}


{% block base_content %}
<h1>Comparisons</h1>

{% if comparisons %}
    <table class="table table-hover">
        <thead>
            <!-- <tr>
                <th>name</th>
                <th>description</th>
            </tr>
            --!>
        </thead>
        <!-- <th>documents</th>
        <th>total sentences</th>
        !-->
        {% for comp in comparisons %}
        <tr>
            <td><a href="{% url 'mtce:comparison_index' comp.id %}">{{ comp.name }}</a></td>
            <td>{{ comp.description }}</td>
            <td><a href="../admin/mtce/comparison/{{ comp.id }}/change/">Edit</a></td>
            <td><a href="../admin/mtce/comparison/{{ comp.id }}/delete/">Delete</a></td>
        </tr>
        {% endfor %}

    </table>
{% else %}
    <p>No comparisons to show.</p>
{% endif %}
    <p><a href="../admin/mtce/comparison/add/">
        <button type="button" class="btn btn-success">Add a new comparison</button>
    </a></p>
{% endblock base_content %}

mtce/templates/mtce/overview_top_menu.html
{% comment %}<div class="collapse navbar-collapse" id="navbarColor01">
{% endcomment %}




<div class="collapse navbar-collapse" id="navbarColor01">

    <ul class="nav nav-pills hav-justified" style="font-size: 20px;">
{% comment %}

    <ul class="navbar-nav mr-auto">
    <ul class="nav nav-pills" style="font-size: 20px;">
{% endcomment %}
        <li class="nav-item">
            <a class="nav-link {% if system %}{% else %}table-primary{% endif %}" href="{% url 'mtce:comparison_index' comparison.id %}">
                <!-- <button type="button" class="btn btn-primary btn-lg nav-link{% if system %} nav-link{% endif %}">
                -->
                {{ comparison.name }}
            </a>
        </li>
        {% if system %}
        <li class="nav-item">
            <a class="nav-link{% if system %} table-primary{% endif %}" href="{% url 'mtce:system_index' system.id %}" >
                 {{ system.name }}
            </a>
        </li>
        {% endif %}
    </ul>
</div>

<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link{% if active == "corpus_metrics" %} active{% endif %}"
       href="{% if system %}{% url 'mtce:system_index' system.id %}{% else %}{% url 'mtce:comparison_index' comparison.id %}{% endif %}">
       Corpus metrics
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == "sentences" %} active{% endif %}"
       href="{% if system %}{% url 'mtce:system_sentences' system.id %}{% else %}{% url 'mtce:comparison_sentences' comparison.id %}{% endif %}">
        Sentences
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == "pairwise" %} active{% endif %}" href="{% url 'mtce:pairwise_index' comparison.id %}">Pairwise diff</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/admin/mtce/comparison/{{ comparison.id }}/change/">Edit</a>
  </li>
</ul>

mtce/templates/mtce/pairwise_diff.html
{% extends 'mtce/pairwise_index.html' %}o


{% block sentence_level_charts %}

<!-- title -->
<h1>{{ checkpoint_A.nicename }} vs {{ checkpoint_B.nicename }}</h1>
<form action="{% url 'mtce:pairwise_diff' comparison.id %}" method="post">
    {% csrf_token %}
    <input class="checkpoint-selection" type="hidden" name="choice[]" id="choice_{{ checkpoint_B.id }}" value="{{ checkpoint_B.id }}">
    <input class="checkpoint-selection" type="hidden" name="choice[]" id="choice_{{ checkpoint_A.id }}" value="{{ checkpoint_A.id }}">
    <button type="submit" class="btn btn-primary">Swap checkpoints</button>
</form>
<hr>
<!-- end title -->

<!-- nav bars -->
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active show" data-toggle="tab" href="#bootstrap">Bootstrap</a>
  </li>
  <li class="nav-item">
    <a class="nav-link show" data-toggle="tab" href="#confirmed">Confirmed n-grams</a>
  </li>
  <li class="nav-item">
    <a class="nav-link show" data-toggle="tab" href="#unconfirmed">Unconfirmed n-grams</a>
  </li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active show" id="bootstrap">

      <!-- start bootstrap charts -->
      <div class="container">
        <div class="row">
            <div class="col-sm">
                {% for ch in sent_level_charts %}
                    <h4>{{ ch.title }}</h4>
                    {{ ch.as_html }}
                {% endfor %}
            </div>
            <div class="col-sm">
                {% for ch in bootstrap_charts %}
                    <h4>{{ ch.title }}</h4>
                    {{ ch.text_result }}
                    {{ ch.as_html }}
                {% endfor %}
            </div>
        </div>
      </div>
      <!-- end bootstrap charts -->

  </div>
  <div class="tab-pane fade" id="confirmed">
      <!-- start confirmed -->
      <div class="container">
          <div class="row">
              {% for n,ntable in confirmed_ngrams %}
                 <div class="col-4">
                    <h4>{{ n }}-grams:</h4>
                   <table class="table table-sm table-hover">
                   {% for ng,a,b,d in ntable %}
                       <tr>
                           <th>
                               {{ ng }}
                           </th>
                           <td>
                               {{ a }} - {{ b }} = {{ d }}
                           </td>
                       </tr>
                   {% endfor %}
                   </table>
                   <hr>
                 </div>
              {% endfor %}
          </div>
      </div>
      <!-- end confirmed -->
  </div>

  <div class="tab-pane fade" id="unconfirmed">
    <!-- start confirmed -->
    <div class="container">
        <div class="row">
            {% for n,ntable in unconfirmed_ngrams %}
                <div class="col-4">
                    <h4>{{ n }}-grams:</h4>
                    <table class="table table-sm table-hover">
                    {% for ng,a,b,d in ntable %}
                        <tr>
                            <th>
                                {{ ng }}
                            </th>
                           <td>
                               {{ a }} - {{ b }} = {{ d }}
                           </td>
                        </tr>
                   {% endfor %}
                   </table>
                   <hr>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- end confirmed -->
  </div>
</div>




{% endblock %}

mtce/templates/mtce/pairwise_index.html
{% extends "mtce/comparison_base.html" %}

{% block comparison_content %}

<script>
$(document).ready(function(){
    $("#button-select-pair").click(function() {
        var checked = [];
        $.each($(".checkpoint-selection:checked"), function() {
            checked.push($(this).val());
        });
        if ((checked.length < 2) || (checked.length > 2)) {
            alert("Select two checkpoints.");
            return false;
        }
    });
});
</script>

    {% block sentence_level_charts %}


    {% endblock %}

    {% comment %}
    #############################################
    Corpus metrics table
    #############################################
    {% endcomment %}

        {% comment %}

<form
        action="{% url 'mtce:pairwise_diff' %}" method="post">
        >
        {% endcomment %}
<form action="{% url 'mtce:pairwise_diff' comparison.id %}" method="post">
<table class="table table-hover">

<thead>
<tr>
  <th scope="col">MT System</th>
  <th scope="col">Checkpoint</th>
    {% for metric in metrics %}
      <th scope="col">{{ metric }}</th>
    {% endfor %}
</tr>
</thead>

<tbody>
{% comment %}
{% endcomment %}
{% csrf_token %}
  {% for sys,cp,metricvalues in systems_checkpoints_metricvalues %}
    <tr class="table-light">
        <th scope="row">
            <input class="checkpoint-selection" type="checkbox" name="choice[]" id="choice_{{ cp.id }}" value="{{ cp.id }}">
            <label for="choice{{ forloop.counter }}">
                <a href="{% url 'mtce:system_index' sys.id %}">{{ sys }}</a>
            </label>
        </th>
      <td>{{ cp }}</td>
        {% for mv in metricvalues %}
          <td>{{ mv }}</td>
        {% endfor %}
     {% comment %}   <td><a href="../../../admin/mtce/comparison/{{ sys.id }}/change/">Edit</a></td>
     {% endcomment %}
    </tr>
  {% endfor %}

  </tbody>
</table>
<button id='button-select-pair' type="submit" class="btn btn-primary">Compare selected pair</button>
</form>

  {% comment %}

</form>
    <p>
<a href="../../../admin/mtce/comparison/{{ sys.id }}/change/">Edit</a>
    </p>

{% endcomment %}

{% endblock comparison_content %}